name: obg
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.0.5
  - blas=1.0
  - bottleneck=1.3.7
  - bowtie2=2.5.4
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.6.2
  - icu=73.2
  - intel-openmp=2023.1.0
  - ipython=8.20.0
  - jedi=0.18.1
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libhwloc=2.10.0
  - libiconv=1.17
  - libstdcxx-ng=13.2.0
  - libuuid=1.41.5
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.2.13
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.3.1
  - pandas=2.2.1
  - parso=0.8.3
  - perl=5.32.1
  - pexpect=4.8.0
  - pip=24.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - python=3.12.3
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - readline=8.2
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tbb=2021.12.0
  - tk=8.6.14
  - traitlets=5.7.1
  - tzdata=2024a
  - wcwidth=0.2.5
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anthropic==0.26.0
      - anyio==4.3.0
      - attrs==23.2.0
      - biopython==1.83
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - dataclasses-json==0.6.6
      - defusedxml==0.7.1
      - distro==1.9.0
      - filelock==3.14.0
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - greenlet==3.0.3
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.23.0
      - idna==3.7
      - jsonpatch==1.33
      - jsonpointer==2.4
      - langchain==0.2.0
      - langchain-anthropic==0.1.13
      - langchain-core==0.2.4
      - langchain-openai==0.1.8
      - langchain-text-splitters==0.2.0
      - langsmith==0.1.73
      - marshmallow==3.21.2
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - openai==1.31.1
      - orjson==3.10.3
      - packaging==23.2
      - primer3-py==2.0.3
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pyyaml==6.0.1
      - regex==2024.5.15
      - requests==2.32.1
      - sniffio==1.3.1
      - sqlalchemy==2.0.30
      - tenacity==8.3.0
      - tiktoken==0.7.0
      - tokenizers==0.19.1
      - tqdm==4.66.4
      - typing-extensions==4.11.0
      - typing-inspect==0.9.0
      - urllib3==2.2.1
      - yarl==1.9.4
